### ISSUE TITLE
XSS vulnerability found

### ISSUE THREAD

**Issue by micaPeralta** [briandusell/stignatiusweb#1]
Hello, i was looking for vulnerabilities for a class assignment and  i have found  that your code is vulnerable to XSS injection. This type of vulnerability allows the attacker to use this on your web page to execute arbitrary JavaScript in a browser and compromise the security of your website.

The following is a simple example that demonstrates vulnerability:

![Captura de pantalla de 2019-06-13 23-17-48](https://user-images.githubusercontent.com/11727581/59478964-a0926080-8e31-11e9-8e6a-7e31d2fda3c8.png)
![Captura de pantalla de 2019-06-13 23-18-08](https://user-images.githubusercontent.com/11727581/59478970-a4be7e00-8e31-11e9-9aae-6413c076c242.png)

To keep yourself safe from XSS, you must sanitize your input. Your application code should never output data received as input directly to the browser without checking it for malicious code. For that you could use any of functions that php provides.You can try escaping HTML input with [htmlspecialchars()](https://www.php.net/manual/en/function.htmlspecialchars.php )  or  can try removing any possible HTML.  [strip_tags()](https://php.net/strip_tags)  is quick and easy.

 I can also suggest you that you use any template engine for PHP, a example can be Twig. Twig auto escapes everything by default,that means that every string printed from a Twig template  gets automatically sanitized. Also you can take advantage of others features, you can see more about that [here]( https://twig.symfony.com/)

That is all. I hope I've helped. Bye!

**Comment by bdusell** [comment]
Hello,

Thank you for bringing this to our attention! This source code repository is out of date and no longer maintained, but we have fixed the issue on the live site.
